### ISSUE TITLE
[style] 어플 UI

### ISSUE THREAD

**Issue by godls20455** [CosineAndroid/GroupFinder#1]
## 기능 설명
- 어플 레이아웃 생성

## To Do
- [x] 공지훈 : 마이 페이지(profile)
- [x] 안진혁 : 게시글 작성(write)
- [x] 권민찬 : 게시글 목록(list)
- [x] 김보라 : 게시글 디테일(detail)
- [x] 마해인 : 네비게이션 드로우(navigation) / 검색(search)

**Comment by bora44144** [comment]
[#1] style: 게시글 디테일
